"""Add expected_delivery and delivered_at fields

Revision ID: 0e582a164550
Revises: 4b4ee7c373be
Create Date: 2025-07-27 14:51:44.072498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e582a164550'
down_revision = '4b4ee7c373be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('selected_color')

    # ### end Alembic commands ###
