"""Add expected_delivery and delivered_at fields

Revision ID: 4b4ee7c373be
Revises: 9c9408befc69
Create Date: 2025-07-27 14:39:13.641231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4ee7c373be'
down_revision = '9c9408befc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('expected_delivery')

    # ### end Alembic commands ###
